#!/usr/bin/env ruby

require "azure_enum"

if (ARGV.length == 0)
  warn "Please provide domain to enumerate on command line. eg azure_enum lolware.net"
  exit
end

puts "Please wait while the given domain is enumerated."
domains = AzureEnum.federated(ARGV[0])
if (!domains || domains == [])
  puts "Unfortunately this domain cannot be enumerated"
  exit
end

puts domains
